RANDOMSEED = 1337
GENERATE_DATA = True
SYNTHETICDATASTRATEGY = None
COLLECTION = "bps"
EPOCHS = 10
INPUT_REPRESENTATIONS = ["BassChromagram38"]
OUTPUT_REPRESENTATIONS = [
    "LocalKey35",
    "PrimaryDegree22",
    "SecondaryDegree22",
    "Inversion4",
    "ChordQuality15",
    "ChordRoot35",
]
SEQUENCELENGTH = 640
BATCHSIZE = 16
COLLECTION = "bps"
DATAAUGMENTATION = True
MODEL = "micchi2020"
SCRUTINIZEDATA = False